### ISSUE TITLE
dealing with 'is owner' 

### ISSUE THREAD

**Issue by beatelite** [mikemclin/angular-acl#14]
So I'm getting close to a release of an app and am starting to go through and protect content/routes using your acl tool. So far so good. 

<dumb question>

I get all the roles and capabilities part in the acl directive. I even have my server as the final authority on submitting content. If a user doesn't have a role with the proper permissions, they can't see content or see the "edit" link.

//begin dumb question
My question: How do I recognize "is owner" in acl?

For example: I have a form that updates a user's profile (validated on the server). It's hooked up properly so the server knows who's logged in. However, people can view other people's profile on the site but the form should only show when they are viewing/editing their own profile.

I can't just give the 'current user' the ability to see the form because then anyone logged in and visiting anyone else's profile will see the form. 

Roles don't seem to make sense here either.

/dumb question

I'm sure I'm missing something. I've been up since 2am so my cognitive focus is about as good as a baby in a strip club. 

Let me know if that makes sense or not. Appreciate any advice.

**Comment by mikemclin** [comment]
This ACL does not deal with ownership.  You would need to add your own logic for displaying edit links, etc when it deals with ownership.
