### ISSUE TITLE
user role permissions level

### ISSUE THREAD

**Issue by sksaini007** [mikemclin/angular-acl#16]
hi,
 i want to   use  user role permissions  is like:  userrole -> module -> permissions.
for Example  
1.  admin-> user management -> (view, add, edit, delete)
2.  member-> user management -> (view, edit)
So please help me for this type user role permissions management.

Thanks,
Sachin Saini

**Comment by mikemclin** [comment]
The service manages the abilities for the current user.  If you are wondering if a particular role can do something, then you shouldn't need my package to do so.

I'm having trouble understanding what you are trying to accomplish.  If you can provide some example code, maybe I can better understand.

**Comment by sksaini007** [comment]
hi,mikemclin
My JSON data is
var aclData = [
	{"super admin":
		[
			{"user management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"order management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"product management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"sales management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"report management":
				["view"],
				["edit"],
				["delete"]
			}			
		]
	},
	{"admin":
		[
			{"user management":
				["add"],
				["view"],
				["edit"]				
			},
			{"order management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"product management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"sales management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"report management":
				["view"],
				["edit"]				
			}			
		]
	},
	{"manager":
		[
			{"user management":
				["add"],
				["view"]								
			},
			{"order management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"product management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"sales management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			},
			{"report management":
				["view"]								
			}			
		]
	},
	{"sales team":
		[			
			{"order management":
				["add"],
				["view"],
				["edit"]				
			},
			{"product management":				
				["view"]								
			},
			{"sales management":
				["add"],
				["view"],
				["edit"],
				["delete"]
			}		
		]
	}
]
[role json.txt](https://github.com/mikemclin/angular-acl/files/126796/role.json.txt)

**Comment by mikemclin** [comment]
The data will need to be transformed/mapped to a compatible format for this plugin.
