### ISSUE TITLE
Protect a route

### ISSUE THREAD

**Issue by brunoneve** [mikemclin/angular-acl#19]
Hi Guys,

in the readme has example to protect a route, I tried and not funcinou, so I made some changes and is now working.

will example if someone needs, using $ routeChangeError

```
    $rootScope.$on('$routeChangeError', function(event, current, previous, rejection){
        console.log(rejection);
        if(rejection === 'Unauthorized'){
            $location.path('home');
        }
    });
```

Att.

**Comment by mikemclin** [comment]
Thanks.  I've updated the README example, adding the `event` param as the first param in the `$routeChangeError` callback function.
