### ISSUE TITLE
How to reload the ACL data before routeProvider resolves?

### ISSUE THREAD

**Issue by alanoliveira** [mikemclin/angular-acl#8]
I'm trying to use AclService.resume() as the example, but when I need reload the ACL data form web it resolves after the routeProvider resolves and denied the access.
Is there some way to prevent the routeProvider resolves until the ACL is successfully loaded?

**Comment by mikemclin** [comment]
I added the ability to run `resume()` during the config phase.  I updated the `README` file.  Let me know if this works for you.

**Comment by mikemclin** [comment]
Closing...
