### ISSUE TITLE
Is there any way make tardy loading ? 

### ISSUE THREAD

**Issue by daruwanov** [mikemclin/angular-acl#9]
My application works with own API server, and i already have, ACL in server side. But i want add some ACL on front-end (hide some buttons with actions etc). And i fond your module. 

But i need initialise ACL after i enter login and password and fetch data from server.(when angular application is working NOT when on config or run part of lifecycle ) 

Is there any way to do this?

**Comment by ravi-mone** [comment]
@daruwanov ,

Daruwanov, I am looking one such ACL, as you said above, Did you come up with any one such module, please suggest me, which is the ACL, you are using.

**Comment by daruwanov** [comment]
@ravi-mone. No, i just  create my own angular module, for this. For now it`s quick solution. It very close for specific of my project.  I want to create  independent version. But it will be a little bit later. 

P.S. so i close this issue\question

**Comment by mikemclin** [comment]
@daruwanov anything that can be done in the **run** phase can be done inside of a controller, service, etc.

So, you can simply inject `AclService` into your controller (or whatever) and use all the methods.

**Comment by daruwanov** [comment]
@mikemclin  Thanks
